Added Mutexes implemented in xtensa-lx6 to prelude & started using in timers example
esp-rs/esp32-hal pull request #31
Opened 2020-06-07 17:40 UTC by arjanmels

Starting point to use standardized Mutex implementation.
This depends on: https://github.com/esp-rs/xtensa-lx6/pull/3.

Should be expanded to be used everywhere inside esp32-hal. However the underlying trait is not yet fully stabilized.

2020-06-12 10:26 UTC, arjanmels commented
Changed to WIP, to wait on the changes in xtensa-lx6 and then use the new traits in all the code.

2020-06-13 13:54 UTC, arjanmels commented
@MabezDev Ok this now updates all usages of interrupt::free and spin::Mutex.
It builds on and therefore includes #34. Propose to review and merge this one to cover both.

2020-06-13 15:04 UTC, MabezDev requested changes

2020-06-13 15:04 UTC, MabezDev commented on examples/timer.rs
> +static TIMER0: CriticalSectionSpinLockMutex<Option<Timer<esp32::TIMG0, Timer0>>> =
Because this example only runs on PRO cpu, wouldn't a `CriticalSectionMutex` suffice?

2020-06-13 15:04 UTC, MabezDev commented on src/clock_control/cpu.rs
> +        xtensa_lx6::interrupt::set_mask(0);
Is this actually necessary? In my experience the mask is 0 on reset, at least for the PRO cpu anyway.

2020-06-13 15:08 UTC, arjanmels commented on examples/timer.rs
> +static TIMER0: CriticalSectionSpinLockMutex<Option<Timer<esp32::TIMG0, Timer0>>> =
Indeed it would. Just using CriticalSectionSpinLockMutex as default so if people extend to multicore, it will still be ok.

2020-06-13 15:09 UTC, arjanmels commented on src/clock_control/cpu.rs
> +        xtensa_lx6::interrupt::set_mask(0);
It may not be necessary, but we did encounter problems on the PRO core with the ccompare registers., it definitly does not hurt.

2020-06-22 15:17 UTC, arjanmels commented
@MabezDev I rebased to current master. For me ready to merge. You still had two request for change, what do you think with my input?

2020-06-23 21:45 UTC, MabezDev commented
I've just released the new versions of lx6-rt and lx6, this should be good to merge once this is updated :)

Sorry this took a while, busy week!

2020-06-24 04:55 UTC, arjanmels commented
No worries, it is a side activity for all of us. 

I already anticipated the change so the versions are already at 0.2.0 and 0.3.0.

2020-06-24 12:14 UTC, merged

2020-06-24 21:42 UTC, reitermarkus commented on Cargo.toml
> -esp32 = { version = "0.5.0", default-features = false }
This broke the `no-rt` functionality.