Renamed GPIO and RTC_IO register field to strip common prefix.
esp-rs/esp32-hal pull request #36
Opened 2020-06-14 18:06 UTC by arjanmels

This depends on https://github.com/esp-rs/esp32/pull/34.
This does not yet address bugfixes, it only includes register field names, which simplifies gpio macros.

(It builds on #34: when this is merged #34 and #31 are also included.)

2020-06-14 21:47 UTC, arjanmels commented
Changed this to WIP so I can include more changes in one go.

2020-06-22 19:29 UTC, arjanmels commented
@MabezDev and @chocol4te I think this is in pretty good shape now. Your review and feedback is most welcome. (Todo's are intterrupt handling and perhaps some more functionality on the RTC_MUX.)

2020-06-23 13:37 UTC, fmckeogh requested changes
Just some really small comment/formatting changes suggested, looks really solid and can't think of anything to change in the implementation!

2020-06-23 13:37 UTC, chocol4te commented on src/clock_control/mod.rs
> +    /// This function can usually take up to one RTC clock cycles (~300us).
```suggestion
    /// This function can usually take up to one RTC clock cycle (~300us).
```

2020-06-23 13:37 UTC, chocol4te commented on src/gpio/mod.rs
> +/// Extension trait to split a GPIO peripheral in independent pins and registers
```suggestion
/// Extension trait to split a GPIO peripheral into independent pins and registers
```

2020-06-23 13:37 UTC, chocol4te commented on src/gpio/mod.rs
> +    /// The to split the GPIO into
```suggestion
    /// The type to split the GPIO into
```

2020-06-23 13:37 UTC, chocol4te commented on src/gpio/mod.rs
> +    fn connect_input_to_peripheral(&mut self, signal: InputSignal) -> &mut Self;
```suggestion
    /// all the options to false.
    fn connect_input_to_peripheral(&mut self, signal: InputSignal) -> &mut Self;
```

2020-06-23 13:37 UTC, chocol4te commented on src/gpio/mod.rs
> +                };
```suggestion
                let af = if force_via_gpio_mux {
                    AlternateFunction::Function3
                } else {
                    match signal {
                        $( $(
                            OutputSignal::$af_signal => AlternateFunction::$af,
                        )* )?
                        _ => AlternateFunction::Function3
                    }
                };
```

2020-06-23 13:37 UTC, chocol4te commented on src/gpio/mod.rs
> +                if af== AlternateFunction::Function3 && signal as usize > 256 {
```suggestion
                if af == AlternateFunction::Function3 && signal as usize > 256 {
```

2020-06-23 13:37 UTC, chocol4te commented on src/gpio/mod.rs
> +                let clipped_signal= if (signal as usize) <= 256 {signal as u16} else {256};
```suggestion
                let clipped_signal = if signal as usize <= 256 { signal as u16 } else { 256 };
```

2020-06-23 14:54 UTC, arjanmels commented
> Just some really small comment/formatting changes suggested, looks really solid and can't think of anything to change in the implementation!

Thanks, always nice to put the dots on the i's and cross the t's. :-)

2020-06-24 14:05 UTC, arjanmels commented
In principle, I think this is ready for merge: https://github.com/esp-rs/esp32/pull/34 has been merged as well as #34. Also the problems @chocol4te was having are solved (https://github.com/esp-rs/esp32-hal/pull/26#issuecomment-648833861).

However, I could still add interrupt support and more extensive support for the RTC IO mux. I will be working on this over the next day/weekend; I can merge it in this PR or can make a new one.

2020-06-24 14:27 UTC, chocol4te commented
@arjanmels imho it might be slightly easier to merge this and have separate PRs for the additional functionality, but I’m also happy to just rebase against this branch when I finish up the I2C work :)

2020-06-24 21:47 UTC, MabezDev requested changes
Great work @arjanmels ! I think it's best to merge this as is, as if the diffs get much bigger I'll need 1 hour to read through ;), but in all seriousness this is a well needed change! I also believe this approach is novel among Rust HAL designs so it will be interesting to see how it plays out!

2020-06-24 21:47 UTC, MabezDev commented on Cargo.toml
> +esp32 = "0.5.0"
```suggestion
esp32 = "0.6.0"
```

2020-06-24 21:53 UTC, merged