Blocking I2C
esp-rs/esp32-hal pull request #55
Opened 2021-03-11 04:39 UTC by hanhossain

This takes the changes made in #26 and adds onto them. Tested with the SSD1306 (using the Heltec LoRa 32 board) and the MPU6050.

Thank you @fmckeogh for the groundwork!

2021-03-11 18:12 UTC, MabezDev commented
Awesome! I'll take this out for a spin this weekend!

2021-04-02 02:09 UTC, hanhossain commented
Hey @MabezDev, friendly bump :)

2021-04-04 18:27 UTC, MabezDev requested changes
@hanhossain my deepest apologies, I started this review and got side tracked by other things. I just had a few comments on the actual implementation. Unfortunately I have not yet had the chance to try this on actual hardware, but I will do this as soon as possible.

2021-04-04 18:27 UTC, MabezDev commented on src/i2c.rs
> +    fn is_i2c0(&self) -> bool {
Perhaps we could add a method to the `Instance` trait to determine which i2c instance this is? Similiar to the way the SPI Instance trait does it.

2021-04-04 18:27 UTC, MabezDev commented on src/i2c.rs
> +        let half_cycle = ((80_000_000 / freq) / 2) as u16;
I was surprised that this is actually a fixed constant, but after looking at the idf implementation it seems it is! Perhaps we should pull this out into a name `const`?

2021-04-04 18:27 UTC, MabezDev commented on src/i2c.rs
> +const DPORT_BASE_ADDR: u32 = 0x3FF4_0000;
This is the address of the `UART0`peripheral? Should this actually be `0x3FF0_0000` as per section 2.3.5 of tfm?

2021-04-14 04:15 UTC, hanhossain commented on src/i2c.rs
> +    fn is_i2c0(&self) -> bool {
Good call, I'll move this method into the trait

2021-04-14 04:56 UTC, hanhossain commented on src/i2c.rs
> +const DPORT_BASE_ADDR: u32 = 0x3FF4_0000;
No, there's a panic on startup when setting it as `0x3FF0_0000`:
```
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0048,len:12
ho 0 tail 12 room 4
load:0x3fff0054,len:4800
load:0x40078000,len:17448
load:0x4007c428,len:4840
entry 0x4007c6a0
----- PANIC -----
PanicInfo { payload: Any, message: Some(called `Result::unwrap()` on an `Err` value: InvalidChipId(0)), location: Location { file: "examples/i2c.rs", line: 98, col: 30 } }
```

What's interesting is under §2.3.5, the notice says:

> Peripherals accessed by the CPU via 0x3FF40000 ~ 0x3FF7FFFF address space (DPORT address) can also be accessed via 0x60000000 ~ 0x6003FFFF (AHB address). (0x3FF40000 + n) address and (0x60000000 + n) address access the same content, where n = 0 ~ 0x3FFFF.

So I guess the DPORT register is at `0x3FF0_0000` however peripheral access starts at `0x3FF4_0000`.

2021-04-14 05:08 UTC, hanhossain commented on src/i2c.rs
> +        let half_cycle = ((80_000_000 / freq) / 2) as u16;
Refactored it into a `SOURCE_CLK_FREQ` const

2021-04-17 15:53 UTC, MabezDev commented
Perfect! Thanks for the contribution @hanhossain!

2021-04-17 15:53 UTC, merged